name: cache_example.yaml

defaults:
  run:
    shell: bash

on:
  # push:
  # branches-ignore:
  #   - "main"

  workflow_dispatch:
    inputs:
      home:
        description: "Debug"
        required: false

jobs:
  first:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Cache node_modules
        id: cache
        uses: actions/cache@v2
        with:
          path: ./tmp.txt
          key: ${{ runner.os }}--${{ hashFiles('**/tmp.txt') }}
      - run: date > tmp.txt
  second:
    needs: first
    runs-on: ubuntu-20.04
    steps:
      - name: Cache node_modules
        id: cache
        uses: actions/cache@v2
        with:
          path: ./tmp.txt
          key: ${{ runner.os }}--${{ hashFiles('**/tmp.txt') }}
      - run: cat tmp.txt
