name: reusable caller

defaults:
  run:
    shell: bash
    working-directory: /go/src/github.com/ttsakai

on:
  workflow_dispatch:
    inputs:
      home:
        description: "Debug"
        required: false

jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflow/called_workflow.yaml
        with:
          value: value from caller
