name: reusable caller

defaults:
  run:
    shell: bash
    working-directory: /go/src/github.com/ttsakai

on:
  # push:
  workflow_dispatch:
    inputs:
      home:
        description: "Debug"
        required: false

jobs:
  call_reusable:
    uses: ./.github/workflows/called_workflow.yaml
    with:
      value: value from caller
