name: CD

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
    branches-ignore:
      - main
  workflow_dispatch:
    inputs:
      home:
        description: "Debug"
        required: false

jobs:
  setup:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.16.0"

  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"
        id: extract_branch

      - name: Set Environment variables
        id: set_env
        run: |
          if [ ${{ steps.extract_branch.outputs.branch }} -eq "master"]; then
            echo "::set-output name=image_tag::${{ steps.extract_branch.outputs.branch }}_${GITHUB_SHA:0:7}"
          else
            echo "::set-output name=image_tag::${{ steps.extract_branch.outputs.branch }}"
          fi
      - run: echo "$GITHUB_CONTEXT
