name: CI

defaults:
  run:
    shell: bash
    working-directory: /go/src/github.com/ttsakai

on:
  push:
  # branches-ignore:
  #   - "main"

  workflow_dispatch:
    inputs:
      home:
        description: "Debug"
        required: false

jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Test
        uses: ./.github/actions/golang/test

      - name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
      - uses: ./.github/actions/golang/test
        id: set_env
        with:
          project_id: test_project

      - name: show output
        run: |
          echo  ${{ steps.set_env.outputs.cluster_name }}
          echo  ${{ steps.set_env.outputs.cluster_location }}
