name: CI

defaults:
  run:
    shell: bash
    working-directory: /go/src/github.com/ttsakai

on:
  push:
    branches-ignore:
      - "main"

  workflow_dispatch:
    inputs:
      home:
        description: "Debug"
        required: false

jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      # - id: foo
      #   uses: ttsakai/composite-action@v1.5
      #   with:
      #     who-to-greet: "Mona the Octocat"
      # - run: echo random-number ${{ steps.foo.outputs.random-number }}
      #   shell: bash
      # - run: exit 1
      - name: Test
        uses: ./.github/actions/golang/test
